help:
	@: # Print this help
	@printf 'Usage: make TARGET\n\n'
	@printf 'Run make with one of the following targets:\n'
	@awk ' \
		/^[^\t:]+:/ { \
			split($$0, s, ":"); \
			cmd=s[1]; \
		} /^\t@: #/ { \
			split($$0, t, ": # "); \
			body=t[2]; \
			doprnt=1; \
		} { \
			if (doprnt == 1) { \
				if (cmd != "") { \
					printf("\n\033[33m%s\033[0m:\n", cmd); \
					cmd="" \
				}; \
				printf("\t%s\n", body); \
				doprnt=0; \
				body=""; \
			}; \
		} \
	' Makefile


.PHONY: run
run:
	@: # Run service and restart on code changes.
	@: # This command requires `watchexec` to be installed (see README).
	watchexec \
		--restart --verbose --clear --wrap-process=session \
		--stop-signal SIGTERM --exts gleam --watch src/ -- "DATABASE_URL=postgresql://postgres:1234@127.0.0.1:5432/app gleam run"

.PHONY: dbup
dbup:
	@: # Start the PostgreSQL server in a docker container.
	@: # This command requires docker to be installed (see README).
	docker run --rm -P \
	    -p 127.0.0.1:5432:5432 \
	    -e POSTGRES_PASSWORD="1234" \
	    -e POSTGRES_USER="postgres" \
	    -e POSTGRES_DB="app" \
	    --name pg postgres:alpine

.PHONY: dbdown
dbdown:
	@: # Stop the PostgreSQL server running in a docker container.
	@: # This command requires docker to be installed (see README).
	docker stop pg || true
	docker ps

.PHONY: url
url:
	@: # Print the database url so you can connect to the db with other tools
	echo "DATABASE_URL=postgresql://postgres:1234@127.0.0.1:5432/app"

.PHONY: migrate
migrate:
	@: # Run the cigogne database migration.
	@: # This is currently disabled b/c cigogne isn't picking up the DATABASE_URL.
	@: # Currently running the migrations as part of application startup.
	echo "!!! This command is currently disabled !!!"
	echo "DATABASE_URL=postgresql://postgres:1234@127.0.0.1:5432/app gleam run -m cigogne up"

.PHONY: squirrel
squirrel:
	@: # Run squirrel dao generator (sort of like a dao, anyway)
	@: # This command is idempotent, and only affects the files under the sql directories, so
	@: # feel free to run this whenever. It does not clobber the models, just the autogenerated files
	@: # under the sql directories.
	DATABASE_URL=postgresql://postgres:1234@127.0.0.1:5432/app gleam run -m squirrel

.PHONY: psql
psql:
	@: # Launch psql client and view the db
	psql postgresql://postgres:1234@127.0.0.1:5432/app
